name: Démonstration CI
on: push

jobs:
  intit:
    runs-on: ubuntu-latest
    steps:
      - name: Etape 1 - Installation
        run: echo "Etape 1 - Installation"
      - name: Etape 2 - Récuperation du code
        run: echo "Etape 2 - Récuperation du code"
      - name: Etape 3 - Build
        run: echo "Etape 3 - Build"
      - name: Etape 4 - Tests
        run: echo "Etape 4 - Tests"
      - name: Etape 5 - Packaging
        run: echo "Etape 5 - Packaging"
      - name: Etape 6 - Fin du pipeline
        run: echo "Etape 6 - Fin du pipeline"

